# Generated by Django 6.1 on 2026-09-11 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technology', 'Tech'), ('creative', 'Creative'), ('leisure', 'Leisure')], max_length=32)),
            ],
        ),
    ]
