# Generated by Django 6.1 on 2026-09-11 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('elementary', 'Sekolah Dasar'), ('middle', 'Sekolah Menengah Pertama'), ('high', 'Sekolah Menengah Atas'), ('bachelor', 'S1'), ('master', 'S2'), ('doctorate', 'S3')], max_length=16)),
                ('admission_year', models.PositiveSmallIntegerField()),
                ('ongoing', models.BooleanField(default=False)),
            ],
        ),
    ]
