# Generated by Django 6.1 on 2026-10-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_interest_starred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
